example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from mywatchlist.views import show_mywatchlist, send_watchlist_xml, send_watchlist_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', send_watchlist_xml, name='send_watchlist_xml'),
    path('json/', send_watchlist_json, name='send_watchlist_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

# TODO: Implement Routings Here
urlpatterns = [
    path('admin/', admin.site.urls),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from todolist.views import show_todolist, register, login_user, logout_user, create_list, get_todolist_json, add_todolist

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_list, name='create_list'),
    path('json/', get_todolist_json, name='get_todolist_json'),
    path('add/', add_todolist, name='add_todolist'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from logging.handlers import WatchedFileHandler
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_catalog_item = CatalogItem.objects.all()
    context = {
        'list_item': data_catalog_item,
        'nama': 'Sasha Nabila Fortuna'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# TODO: Create your views here.
def show_mywatchlist(request):
    data_watchlist_item = MyWatchList.objects.all()
    var_have_watched = 0
    var_not_watched = 0
    for films in data_watchlist_item:
        if films.watched == "Sudah":
            var_have_watched += 1
        else:
            var_not_watched += 1
    notif = ""
    if(var_have_watched < var_not_watched):
        notif = "Wah, kamu masih sedikit menonton!"
    else:
        notif = "Selamat, kamu sudah banyak menonton!"
    context = {
        'list_movies': data_watchlist_item,
        'nama': 'Sasha Nabila Fortuna',
        'npm': '2106632226',
        'pesan' : notif
    }
    return render(request, "mywatchlist.html", context)

def send_watchlist_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def send_watchlist_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import render
from todolist.models import Task

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms


# TODO: Create your views here.
class TaskForm(forms.Form):
    title = forms.CharField(label="Judul")
    description = forms.CharField(label="Deskripsi", widget=forms.Textarea)

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = Task.objects.filter(user=request.user).all()
    context = {
        'list_todo': data_todolist,
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def get_todolist_json(request):
    data_todolist = Task.objects.filter(user=request.user).all()
    return HttpResponse(serializers.serialize("json", data_todolist), content_type="application/json")

@login_required(login_url='/todolist/login/')
def add_todolist(request):
    if request.method == "POST":
        date = datetime.date.today()
        title = request.POST.get("title")
        description = request.POST.get("description")
        user = request.user

        new_todo = Task(user=user, date=date, title=title, description=description)
        new_todo.save()

        return HttpResponse(status=200)
    return redirect("todolist:show_todolist")

def create_list(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            todo = Task(date = datetime.date.today(), 
                        title = form.cleaned_data["title"],
                        description = form.cleaned_data["description"],
                        user = request.user,)
            todo.save()
            messages.success(request, "Task Berhasil Disimpan")
            return redirect("todolist:show_todolist")
    form = TaskForm()
    context = {"form": form}
    return render(request, "create.html", context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>2106632226</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for items in list_item %}
        <tr>
            <th>{{items.item_name}}</th>
            <th>{{items.item_price}}</th>
            <th>{{items.item_stock}}</th>
            <th>{{items.rating}}</th>
            <th>{{items.description}}</th>
            <th>{{items.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Third Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for items in list_movies %}
        <tr>
            <th>{{items.watched}}</th>
            <th>{{items.title}}</th>
            <th>{{items.rating}}</th>
            <th>{{items.release_date}}</th>
            <th>{{items.review}}</th>
        </tr>
    {% endfor %}
  </table>

  <h5>Message: </h5>
  <p>{{pesan}}</p>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="jquery-3.6.0.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create Task</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        body {
            background: #FFE6F7;
        }

        .login th{
            padding: 10px 10px 10px 10px;
        }

        td{
            max-width: 200px;
        }

        textarea{
            max-width: 200px;
        }

        .login {
            max-width: 400px;
            min-height: 500px;
            margin: 160px auto;
            padding: 40px 30px 30px 30px;
            background-color: #FFE6F7;
            border-radius: 15px;
            box-shadow: 13px 13px 20px #C3B1E1, -13px -13px 20px #CCCCFF;
            align-items: center;
        }

        .login .name {
            font-weight: 600;
            font-size: 1.4rem;
            letter-spacing: 1.3px;
            padding-left: 10px;
            color: #555;
        }

        .submit {
            box-shadow: none;
            width: 100%;
            height: 40px;
            background-color: violet;
            color: #fff;
            border-radius: 20px;
            box-shadow: 3px 3px 3px #b1b1b1,-3px -3px 3px #fff;
            letter-spacing: 1.3px;
        }

        .submit:hover {
            background-color: #5d3fd3;
        }

        .text-center{
            padding-bottom: 10px;
        }

        .login input{
            max-width: 200px;
        }

        @media(max-width: 430px) {
            .login {
                margin: 30px 20px;
                padding: 40px 15px 15px 15px;
            }
        }
    </style>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class = "login">
        <div class="text-center mt-4 name">
            Buat Task
        </div>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input class=submit type="submit" value="Buat"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
    </div>
  </body>
</html>

todolist/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        body {
            background: #FFE6F7;
        }

        .login {
            max-width: 350px;
            min-height: 500px;
            margin: 80px auto;
            padding: 40px 30px 30px 30px;
            background-color: #FFE6F7;
            border-radius: 15px;
            box-shadow: 13px 13px 20px #C3B1E1, -13px -13px 20px #CCCCFF;
        }

        .login .name {
            font-weight: 600;
            font-size: 1.4rem;
            letter-spacing: 1.3px;
            padding-left: 10px;
            color: #555;
        }

        .login .form-field input {
            width: 100%;
            display: block;
            border: none;
            outline: none;
            background: none;
            font-size: 1.2rem;
            color: #666;
            padding: 10px 15px 10px 10px;
        }

        .login .form-field {
            padding-left: 10px;
            margin-bottom: 20px;
            border-radius: 20px;
            box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;
        }

        .login .form-field .fas {
            color: #555;
        }

        .login .btn {
            box-shadow: none;
            width: 100%;
            height: 40px;
            background-color: violet;
            color: #fff;
            border-radius: 25px;
            box-shadow: 3px 3px 3px #b1b1b1,-3px -3px 3px #fff;
            letter-spacing: 1.3px;
        }

        .login .btn:hover {
            background-color: #CBC3E3;
        }

        .login a {
            text-decoration: none;
            font-size: 1.0rem;
            color: violet;
        }

        .login a:hover {
            color: purple;
        }

        @media(max-width: 380px) {
            .login {
                margin: 30px 20px;
                padding: 40px 15px 15px 15px;
            }
        }
    </style>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class = "login">
        <div class="text-center mt-4 name">
            Login
        </div>
    
        <form method="POST" action="" class="p-3 mt-3">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="far fa-user"></span>
                <input type="text" name="username" placeholder="Username" class="form-control">
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <input type="password" name="password" placeholder="Password" class="form-control">
            </div>
            <button class="btn mt-3">Login</button>
        </form>   
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        <div class="text-center fs-6">
            Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
        </div>
    </div>
  </body>
</html>

todolist/templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register Account</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }
        body {
            background: #FFE6F7;
        }

        td{
            padding: 10px 10px 10px 10px;
        }

        .login {
            max-width: 600px;
            min-height: 500px;
            margin: 80px auto;
            padding: 40px 30px 30px 30px;
            background-color: #FFE6F7;
            border-radius: 15px;
            box-shadow: 13px 13px 20px #C3B1E1, -13px -13px 20px #CCCCFF;
        }

        .login .name {
            font-weight: 600;
            font-size: 1.4rem;
            letter-spacing: 1.3px;
            padding-left: 10px;
            color: #555;
        }

        .submit {
            box-shadow: none;
            width: 100%;
            height: 40px;
            background-color: violet;
            color: #fff;
            border-radius: 20px;
            box-shadow: 3px 3px 3px #b1b1b1,-3px -3px 3px #fff;
            letter-spacing: 1.3px;
        }

        .submit:hover {
            background-color: #5d3fd3;
        }

        .text-center{
            padding-bottom: 10px;
        }

        @media(max-width: 630px) {
            .login {
                margin: 30px 20px;
                padding: 40px 15px 15px 15px;
            }
        }
    </style>
  </head> 
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class = "login">
        <div class="text-center mt-4 name">
            Formulir Registrasi
        </div>
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input class="submit" type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>
    
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    
    </div>
  </body>
</html>

todolist/templates/todolist.html
{% extends 'base.html' %}
{% block meta %}
  <title>Welcome, {{user.get_username}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;
    }

    body{
      background: #FFE6F7;
      margin-top:20px;
    }

    .card-margin {
        margin-bottom: 1.875rem;
    }

    .card {
        border: 0;
        box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
        -webkit-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
        -moz-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
        -ms-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
    }
    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #cbc3e3;
        background-clip: border-box;
        border: 1px solid #e6e4e9;
        border-radius: 8px;
    }

    .card:hover{
      transform: scale(1.1);
      background-color: violet;
    }

    .card-title{
      font-weight: bold;
    }

    .card .card-header.no-border {
        border: 0;
    }

    .card .card-header {
        background: none;
        padding: 0 0.9375rem;
        font-weight: 500;
        display: flex;
        align-items: center;
        min-height: 50px;
    }

    .card-header:first-child {
        border-radius: calc(8px - 1px) calc(8px - 1px) 0 0;
    }

    .widget-49 .widget-49-title-wrapper {
      display: flex;
      align-items: center;
      font-weight: bold;
    }

    .widget-49 .widget-49-title-wrapper .widget-49-date-primary {
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      background-color: #edf1fc;
      width: 4rem;
      height: 4rem;
      border-radius: 10px;
      margin-left: 10px;
    }

    .widget-49 .widget-49-title-wrapper .widget-49-date-primary .widget-49-date {
      color: #4e73e5;
      line-height: 1;
      font-size: 1rem;
      text-transform: uppercase;
      text-align: center;
    }

    .widget-49 .widget-49-title-wrapper .widget-49-meeting-info {
      display: flex;
      flex-direction: column;
      margin-left: 1rem;
      font-weight: bold;
    }

    .widget-49 .widget-49-title-wrapper .widget-49-meeting-info .widget-49-pro-title {
      color: #3c4142;
      font-size: 14px;
      margin-right: 5px;
    }

    .todos a, .btn{
      margin: 10px 10px 10px 10px;
      text-align: center;
      box-shadow: none;
      width: 60%;
      height: 40px;
      background-color: violet;
      color: #fff;
      border-radius: 25px;
      box-shadow: 3px 3px 3px #b1b1b1,-3px -3px 3px #fff;
      letter-spacing: 1.3px;
    }

    .todos {
      max-width: 750px;
      min-height: 500px;
      margin: 80px auto;
      padding: 40px 30px 30px 30px;
      background-color: #FFE6F7;
      border-radius: 15px;
      box-shadow: 13px 13px 20px #C3B1E1, -13px -13px 20px #CCCCFF;
    }

    .todos .name {
      font-weight: 600;
      font-size: 30px;
      letter-spacing: 1.3px;
      padding-left: 10px;
      color: #555;
    }

    .todos a:hover{
      background-color: #CBC3E3;
    }

    .btn:hover{
      background-color: #CBC3E3;
    }

    @media(max-width: 780px) {
          .login {
              margin: 30px 20px;
              padding: 40px 15px 15px 15px;
          }
    }
  </style>
{% endblock meta %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<div class="todos">
  <div class="text-center mt-4 name">
    Todolist
  </div>
  <div class="text-center fs-6">
    Welcome, {{user.get_username}}!
  </div>

  <div class="container-md">
    <div class="">
      <p align="center" style="padding-top: 15px">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#formModal" data-whatever="{% url 'todolist:show_todolist' %}">Add Task</button>
      </p>
    </div>
    <div class="row" id="idCard">
      {% for items in list_todo %}
      {% empty %}
    </div>
    {% endfor %}
  </div>

  <p align="center">
    <a href="{% url 'todolist:logout' %}" class="btn btn-primary">Logout</a>
  </p>
</div>

<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="formModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #CF9FFF;">
        <h1 class="modal-title fs-5" id="formModalLabel" style="font-weight: bold;">New todolist</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'todolist:add_todolist' %}" method="post" id="form-task">
        {% csrf_token %}
        <div class="modal-body" style="background-color: #FFE6F7;">
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Title</label>
            <input type="text" class="form-control" name="title" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Description</label>
            <textarea class="form-control" name="description" id="message-text"></textarea>
          </div>
        </div>
        <div class="modal-footer" style="background-color: #FFE6F7;">
          <input class="btn btn-primary" type="submit" name="submit" value="Create Task" />
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  function getTask(){
    $("#idCard").empty();
    $.getJSON("{% url 'todolist:get_todolist_json' %}", function(data) {
        $(data).each(function(i,entry){
            $("#idCard").append(
              $('<div class="col-lg-4">').append(
                $('<div class="card card-margin">').append(
                  $('<div class="card-header no-border">').append(
                    $('<h5 class="card-title">').append(
                      entry.fields.title
                    )
                  )
                ).append(
                  $('<h5 class="card-title">').append(
                      $('<div class="widget-49">').append(
                        $('<div class="widget-49-title-wrapper">').append(
                          $('<div class="widget-49-date-primary">').append(
                            $('<span class="widget-49-date">').append(
                              entry.fields.date
                            )
                          )
                        ).append(
                          $('<div class="widget-49-meeting-info">').append(
                              $('<span class="widget-49-pro-title">').append(
                                entry.fields.description
                              )
                          )
                        )
                      )
                    )
                )
              )
            )
        })
    })

      .done(function(){
        console.log("data loaded!");
    })

    .fail(function(e){
        console.log('error:');
        console.error(e);
    });
  }

  const formModal = document.getElementById('formModal')
    formModal.addEventListener('show.bs.modal', event => {
      // Button that triggered the modal
      const button = event.relatedTarget
      // Extract info from data-bs-* attributes
      const recipient = button.getAttribute('data-bs-whatever')
      // If necessary, you could initiate an AJAX request here
      // and then do the updating in a callback.
      //
      // Update the modal's content.
      const modalTitle = formModal.querySelector('.modal-title')
      const modalBodyInput = formModal.querySelector('.modal-body input')

      modalTitle.textContent = `New TODOLIST`
      modalBodyInput.value = recipient
    })

  $(document).ready(function(){
      getTask();
      $('#form-task').submit(function (event) {
        event.preventDefault();
    
        $.ajax({
            type: "POST",
            url: "{% url 'todolist:add_todolist' %}",
            data: $(this).serialize(),
            success: function(response){
                $("#formModal").modal('toggle');
                $("#form-task > div > .form-control").each(function (i) {
                    $(this).val("");
                })
                getTask();
            },
            error: function(xhr, resp, text) {
                console.log("create-task POST ERROR")
                console.log(xhr, resp, text);
            }
        }).done(function (data) {
            console.log(data);
        });
    
        });
  });
</script>
{% endblock content %}